from os.path import join
import yaml
if not workflow.overwrite_configfiles:
    configfile: "config.yml"

wf_path = config["wf_local"]
wf_local = join(wf_path, "config.yaml")
with open(wf_local, 'r') as f:
    qos_type = yaml.safe_load(f)

def get_qos(rule_name):
    return qos_type[rule_name] if rule_name in qos_type else qos_type['default-resources']

def get_fastq(data, key):
    d_map = OrderedDict({"read1":"R1", "read2":"R3", "barcode":"R2"})
    # data_name = "_".join(wildcards.data.split("_")[:-1])
    data_name = "_".join(data.split("_")[:-1])
    return [join(atac_data_path, data, f"{data_name}_S3_L00{x}_{d_map[key]}_001.fastq.gz") for x in Ls]

input_ref_file = config["ref_fasta_input"]

### data path
atac_data_path = config["raw_data_dir"]
data_names = config["data_names"]

### fastqs
Ls = [1,2]
data_name = "_".join("{data}".split("_")[:-1])

include:"run_chromap/run_chromap_index.smk"
include:"run_chromap/chromap_map.smk"
include:"run_piscem/run_piscem_index.smk"
include:"run_piscem/run_piscem_map.smk"


rule all:
    input:
        rules.all_chromap_index.input,
        rules.all_piscem_ind.input,
        rules.all_piscem_map.input,
        rules.all_chromap_map.input

