from os.path import join
import yaml
if not workflow.overwrite_configfiles:
    configfile: "config.yml"

wf_path = config["wf_local"]
wf_local = join(wf_path, "config.yaml")
with open(wf_local, 'r') as f:
    qos_type = yaml.safe_load(f)

def get_qos(rule_name):
    return qos_type[rule_name] if rule_name in qos_type else qos_type['default-resources']

input_ref_file = config["ref_fasta_input"]

include:"run_chromap/run_chromap_index.smk"
include:"run_piscem/run_piscem_index.smk"
include:"run_piscem/run_piscem_map.smk"

rule all:
    input:
        rules.all_chromap_index.input,
        rules.all_piscem_ind.input,
        rules.all_piscem_map.input

