### k,m, reference, parameters
k: [25]
#m: [17,19]
m: [17]
#thr: [0.7,1]
thr: [0.7]
bin_size: [1000]
kmers_orphans: ["false"]
ref_fasta_input: 
 hg38: /fs/nexus-projects/scATAC-seq/reference/GRCh38-2020-A-build/Homo_sapiens.GRCh38.dna.primary_assembly.fa
 mm10: /fs/nexus-projects/scATAC-seq/reference/mm10-2020-A-build/Mus_musculus.GRCm38.dna.primary_assembly.fa.modified
whitelist_map:
  atac: /fs/cbcb-lab/rob/students/noor/Atacseq/cellranger-atac-2.1.0/lib/python/atac/barcodes/737K-cratac-v1.txt

tmp_dir: "/scratch1"
q_macs2: 0.1
g_macs2: "hs"

threads: [4,8,12,16,20,24,32]

### Output path
pisc_output_path: "/mnt/scratch3/noor/scAtacSeq/analysis/piscem_timing"
chromap_output_path: "/mnt/scratch3/noor/scAtacSeq/analysis/chromap"

### Software
piscem_path: "/mnt/scratch3/noor/scAtacSeq/piscem"
alevin_fry_path: "/mnt/scratch3/noor/scAtacSeq/alevin-fry/target/release/alevin-fry"
chromap_path: "/mnt/scratch3/noor/scAtacSeq/chromap/chromap"

# htslib_path: "/fs/cbcb-software/RedHat-8-x86_64/local/htslib/1.16/bin"
# macs2_path: "/fs/cbcb-lab/rob/students/noor/miniforge3/envs/macs2/bin"
# R_path: "/fs/cbcb-lab/rob/students/noor/miniforge3/envs/R4.3/bin"

wf_local: "/fs/nexus-projects/scATAC-seq/snake/snakemake_rules/timing_analysis/wf_local"

### data path
raw_data_dir: "/fs/nexus-projects/scATAC-seq/data"
data_dict: 
  10k_hgmm_ATACv2_nextgem_Chromium_Controller_fastqs:
   org: hg38
   S: 3
   L: [1,2]
   whl_type: atac
   rc: true
  10k_pbmc_ATACv2_nextgem_Chromium_Controller_fastqs:
   org: hg38
   S: 3
   L: [1,2]
   whl_type: atac
   rc: true
  8k_mouse_cortex_ATACv2_nextgem_Chromium_Controller_fastqs:
   org: mm10
   S: 6
   L: [3,4]
   whl_type: atac
   rc: true
  human_brain_3k_fastqs:
   org: hg38
   S: 19
   L: [1,2,3,4]
   whl_type: arc
   rc: false
data_names: ["8k_mouse_cortex_ATACv2_nextgem_Chromium_Controller_fastqs", "10k_pbmc_ATACv2_nextgem_Chromium_Controller_fastqs"]
