executor: slurm
latency-wait: 5
default-resources:
 constraint: EPYC-7313
 slurm_partition: cbcb
 cpus_per_task: 8
 mem_mb: 60000
 slurm_extra: "'--account=cbcb --qos=medium --time=09:10:00 --mail-type=FAIL --mail-user=npsingh@umd.edu'"
 


